### ISSUE TITLE
Typos on the landing page?

### ISSUE THREAD

**Issue by dandv** [smartlook/smartlook.github.io#182]
Sorry since this is the wrong repo, but I couldn't find one of the (very nicely designed BTW) website.

Anyway, just wanted to say that at https://www.smartlook.com/, there's this typo,

> And you see only what you see only what you need to see.

**Comment by Acro** [comment]
@dandv Thanks, will fix.

**Comment by amertak** [comment]
Fixed. Thanks @dandv
