### ISSUE TITLE
Where to find changelogs?!

### ISSUE THREAD

**Issue by lucianomlima** [smartlook/smartlook.github.io#91]
We use the react-native SDK in version 0.7.0 and with `yarn outdated` I can see that the latest version is 0.11.0
Where I find what changes?!

**Comment by Pajk** [comment]
Hello @lucianomlima, sorry for not getting back to you sooner. The changelog for react-native SDK is in a separate repository https://github.com/smartlook/smartlook-react-native-sdk. It's not being updated on a regular basis though. We're already working on the automation of releases and changelogs for all platforms so it'll be much better in the future.
